/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package test8_0

import org.gradle.testfixtures.ProjectBuilder
import org.gradle.api.Project
import spock.lang.Specification

/**
 * A simple unit test for the 'test8_0.greeting' plugin.
 */
class Test8_0PluginTest extends Specification {
    def "plugin registers task"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply("test8_0.greeting")

        then:
        project.tasks.findByName("greeting") != null
    }
}
